name: swma

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - astropy
  - matplotlib
  - numpy
  - pandas
  - streamlit=1.5.1
  - sunpy=3.1.3
  - pytest-astropy
  - pytest-sugar
